### PR TITLE
about postgres

### PR DESCRIPTION
**Pull request by Lobason**

### CODE REVIEW

**Review by prinz0147 — APPROVED** [review]
It sure is. It feels surreal thinking we can talk to a computer, lol.

**Review by nkwatoh1 — COMMENTED** [review]
come see the way i di order the computer with codes. hihihihi

**Comment by Lobason** [comment]
> come see the way i di order the computer with codes. hihihihi

Enjoy lol!

**Comment by PhilipNze** [comment]
Well, I will like to catch up bro

**Review by PhilipNze — COMMENTED** [review]
I will approve it bro.

**Pull request merged**
