### PR TITLE
fun story about myself

### PR DESCRIPTION
**Pull request by frubruce**

### CODE REVIEW

**Review by Ta-tech-solution — APPROVED** [review]
hahaha

**Review by nkwatoh1 — APPROVED** [review]
great

**Review by Lobason — COMMENTED** [review]
There is no space between "The" and "inventor" on line one.

**Review by prinz0147 — APPROVED** [review]
I think this is really solid!

**Review by PhilipNze — APPROVED** [review]
am with you bro

**Review by Lobason — APPROVED** [review]

**Review by nkwatoh1 — APPROVED** [review]

**Review by kbih — APPROVED** [review]
great job mr bruce

**Pull request closed without merging**
